<?php

/**
 * @file
 * General hook implementations.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\embargo_inheritance\EmbargoStorage;

/**
 * Implements hook_entity_type_alter().
 */
function embargo_inheritance_entity_type_alter(array &$entity_types) : void {
  /** @var \Drupal\Core\Entity\EntityTypeInterface[] $entity_types */
  $entity_types['embargo']->setStorageClass(EmbargoStorage::class);
}

/**
 * Implements hook_ENTITY_TYPE_insert() for node entities.
 */
function embargo_inheritance_node_insert(EntityInterface $entity) {
  // Shouldn't really need to do anything on insert: We don't expect nodes to
  // somehow have things already related to them on ingest.
}

/**
 * Implements hook_ENTITY_TYPE_update() for node entities.
 */
function embargo_inheritance_node_update(EntityInterface $entity) {
  // @todo If there's a change to `field_member_of` and there is any difference
  // in the embargoes visible through them, flag any indirect child entities for
  // reindexing.
}

/**
 * Implements hook_ENTITY_TYPE_delete() for node entities.
 */
function embargo_inheritance_node_delete(EntityInterface $entity) {
  // @todo If there's an embargo visible via either this node or this node's
  // `field_member_of` relationship(s), flag indirect child entities for
  // reindexing.
}

/**
 * Implements hook_ENTITY_TYPE_insert() for embargo entities.
 */
function embargo_inheritance_embargo_insert(EntityInterface $entity) {
  // @todo Flag indirect child entities of target node for reindexing.
}

/**
 * Implements hook_ENTITY_TYPE_update() for embargo entities.
 */
function embargo_inheritance_embargo_update(EntityInterface $entity) {
  // @todo Flag indirect child entities of target node for reindexing.
}

/**
 * Implements hook_ENTITY_TYPE_delete() for embargo entities.
 */
function embargo_inheritance_embargo_delete(EntityInterface $entity) {
  // @todo Flag indirect child entities of target node for reindexing.
}
