---
name: PHPUnit Tests
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  PHPUnit:
    uses: discoverygarden/phpunit-action/.github/workflows/phpunit.yml@v1
    secrets: inherit
    with:
      composer_prereqs: >-
        "discoverygarden/islandora_member_of_entailment:dev-implementation as 1.x-dev"
        "discoverygarden/embargo:dev-feature/generalize as 1.x-dev"
      composer_patches: |
        {
          "discoverygarden/islandora_test_support": {
            "AUCIR-198: Node bundle use": "https://patch-diff.githubusercontent.com/raw/discoverygarden/islandora_test_support/pull/6.patch"
          },
          "drupal/core": {
            "https://www.drupal.org/project/drupal/issues/2920527": "https://www.drupal.org/files/issues/2022-01-11/2920527-26.patch"
          }
        }
